name: Draw keymap

on:
  workflow_dispatch:

concurrency:
  group: keymap-drawer-main
  cancel-in-progress: false

jobs:
  draw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate files
        run: |
          echo "run your generator here"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add keymap-drawer/*.svg keymap-drawer/*.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "[Draw] personal v1"
          git pull --rebase origin main
          git push origin HEAD:main
